### ISSUE TITLE
Comma-separated selectors to style multiple elements

### ISSUE THREAD

**Issue by cyouh95** [jstilb/f1-3-c2p1-colmar-academy#3]
You could specify a property for multiple elements at once by separating their selectors with commas:

```css
.menu, .logo { 
   display: none; 
 }
```

https://github.com/jstilb/f1-3-c2p1-colmar-academy/blob/00628a46463f41b85277155840631213ff2cb006/capstone/resources/css/style.css#L91-L97
